name: mobilekampus
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/home.svg 
    - assets/images/CuanM.png
    - assets/icons/artikelactive.svg
    - assets/icons/artikelnonactive.svg
    - assets/icons/profileactive.svg
    - assets/icons/profilenonactive.svg
    - assets/icons/homeactive.svg
    - assets/icons/homenonactive.svg
    - assets/icons/statisticactive.svg
    - assets/icons/statisticnonactive.svg



